### ISSUE TITLE
"How Workers works" page not rendering figures

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/cloudflare-docs#4223] opened 2022-04-26 18:05 UTC
The figures don’t seem to be showing anymore.

https://developers.cloudflare.com/workers/learning/how-workers-works/

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/154613/165363290-4d0783d6-ef50-4da7-983f-1a44183b54b2.png">

https://web.archive.org/web/20220216013511/https://developers.cloudflare.com/workers/learning/how-workers-works

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/154613/165363533-c0dbdf09-8b9b-46a9-896f-995e0c6d70c5.png">

See https://github.com/cloudflare/cloudflare-docs/commit/607d9ffe84fdcc879d1b076901fd4b5cda669d96#r72241045 for details

**Comment by kodster28** [comment] 2022-04-27 14:25
This is referring specifically to https://github.com/cloudflare/cloudflare-docs/blob/production/content/workers/learning/how-workers-works.md?plain=1#L13

**Comment by adamschwartz** [comment] 2022-04-28 22:44
Yea, and https://github.com/cloudflare/cloudflare-docs/blob/05be1e064052b78cb42ec3983906f9811f83dfea/content/workers/learning/how-workers-works.md?plain=1&rgh-link-date=2022-04-27T14%3A25%3A25Z#L25

**Comment by KimJ15** [comment] 2022-05-18 20:40
@deadlypants1973 would you mind taking a look at this issue - if it's a bug can you reassign or close the issue if it is expected behavior because the images were removed. Thanks!!

**Closed as completed** 2022-05-24 19:31 UTC
Labels: documentation, engineering
