### ISSUE TITLE
Extra whitespace in footer after "Edit on GitHub" link

### ISSUE THREAD

**Issue by jbampton** [cloudflare/cloudflare-docs#568] opened 2020-12-31 14:00 UTC
![Screen Shot 2020-12-31 at 11 54 13 pm](https://user-images.githubusercontent.com/418747/103413195-3d5b5100-4bc4-11eb-8acc-eb4e5a5e8e6c.png)

**Comment by jclee** [comment] 2020-12-31 19:44
Looks like the intent is for the dot is to be a separator, not a period, which is why there is extra padding.  The actual character being used is unicode code point 183 -- the `&middot;` HTML entity -- which is a bit higher off of the baseline than a period.  Agreed that the extra spacing makes it harder to tell that the dot is being used this way.  Perhaps a different symbol would be clearer... like maybe a dash, or a lighter/heavier dot?

Looks like the responsible code is actually in the cloudflare-docs-engine repo: https://github.com/cloudflare/cloudflare-docs-engine/blob/master/src/components/docs-footer.js#L25-L27

**Comment by KimJ15** [comment] 2021-04-08 14:18
Closing as not a bug - this is expected behavior.

**Closed as completed by KimJ15** 2021-04-08 14:18 UTC
Labels: bug
