### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by leojonathanoh** [cloudflare/cloudflare-docs#1752] opened 2021-07-09 03:50 UTC
### Expected Behavior

Intact links

### Actual Behavior

Broken links

### Section that requires update

https://github.com/cloudflare/cloudflare-docs/blob/production/products/cloudflare-one/src/content/connections/connect-devices/warp/control-proxy.md#control-proxy-settings

### Additional information

Nil

**Comment by KimJ15** [comment] 2021-07-12 14:56
Hi there - I'm going to close this issue as a duplicate of #1753. We'll work from that PR. Feel free to open a new issue or ask any questions.

**Closed as completed by KimJ15** 2021-07-12 14:56 UTC
Labels: documentation
