### ISSUE TITLE
Angular: Error in Javascript after hosting in Cloudflare pages, works locally in both Development and Production mode.

### ISSUE THREAD

**Issue by meynguy** [cloudflare/cloudflare-docs#12212] opened 2023-12-12 18:11 UTC
### Example URL(s)

I followed this guide https://developers.cloudflare.com/pages/framework-guides/deploy-an-angular-site/ and found 2 errors in the document. I have created an issue about that [here.](https://github.com/cloudflare/cloudflare-docs/issues/12183)

But now I seem to have another error, my code is available in [this repository](https://github.com/meynguy/LearnAngular) which works fine locally both in Development and Production mode but when hosted in Pages, gives a Javascript error in the browser console  https://learnangular.pages.dev/ 

### Actual Behavior

Visit :
https://learnangular.pages.dev/ 

Error in the Javascript in the browser console:

```
main-HYFEYK7Q.js:8 Error: NG0507
    at aC (main-HYFEYK7Q.js:7:81327)
    at useValue (main-HYFEYK7Q.js:7:80970)
    at Hn.resolveInjectorInitializers (main-HYFEYK7Q.js:7:20740)
    at main-HYFEYK7Q.js:7:76508
    at k.invoke (polyfills-LZBJRJJE.js:1:6434)
    at Object.onInvoke (main-HYFEYK7Q.js:7:50028)
    at k.invoke (polyfills-LZBJRJJE.js:1:6374)
    at oe.run (polyfills-LZBJRJJE.js:1:1811)
    at t.run (main-HYFEYK7Q.js:7:48756)
    at Tf (main-HYFEYK7Q.js:7:76497)
```

### Expected Behavior

No error in the browser console

**Comment by katzomri1014** [comment] 2024-02-04 18:57
Is there any new information about this issue? We also encountered the exact same problem using angular 17.

**Comment by deadlypants1973** [comment] 2024-02-06 17:34
Hi @meynguy, we are going to be auditing and testing all the Framework guides to make sure that the instructions are working as intended since they were published. In regard to #12183, @markdembo made a PR to address this issue: https://github.com/cloudflare/cloudflare-docs/pull/12719. As for the rest, please be assured it will get looked at very soon!

**Comment by kodster28** [comment] 2024-04-29 20:23
Howdy @meynguy, took a look at the site you provided and it _seems_ like you've fixed the issues in the console.

Was there something particular that helped fix those? And/or any improvements you'd recommend for our guide?

**Comment by meynguy** [comment] 2024-04-30 08:43
@kodster28 The problem occurs if you try to bind a custom hostname to the Cloudflare page, not sure if that helps, for now I'm just hosting with a different service.

**Comment by kodster28** [comment] 2024-05-01 15:03
Howdy @meynguy, tested with a `custom domain` and it's all working fine for me (at least using the Angular guide).
- [Site](https://kody-with-a-k.com/)
- [Repo](https://github.com/kodster28/angular-test)

If you happened to be referring to `custom hostnames`, meaning something under [Cloudflare for SaaS](https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/), that's sorta outside the scope of that guide.

Going to close this out for now since I can't validate any issues you're experiencing with the guide in question.

**Closed as completed by kodster28** 2024-05-01 15:03 UTC
Labels: bug, product:pages, content:edit, DevRel, bad-example, framework-guides
