### ISSUE TITLE
Command doesn't work

### ISSUE THREAD

**Issue by dmvvilela** [cloudflare/cloudflare-docs#13549] opened 2024-03-20 17:37 UTC
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-a-remix-site/

### What changes are you suggesting?

`npm create cloudflare@latest my-remix-app -- --framework=remix`

### Additional information

`▲  Oh no! The path "templates/vite-cloudflare" was not found in this GitHub repo.`

**Comment by dario-piotrowicz** [comment] 2024-03-20 17:43
@dmvvilela thank you very much for the issue 🙂 

We've already noticed this, it was caused by an upstream change in the Remix repository

we've already fixed it: https://github.com/cloudflare/workers-sdk/pull/5312

The fix should be available shortly as soon as we make a new C3 release 🙂

**Comment by dario-piotrowicz** [comment] 2024-03-21 10:11
@dmvvilela I've just checked and the issue's been resolved 🙂👍 

I'm closing this issue then, if you still have any problem please feel free to reopen this issue or open a new one 🙂

**Closed as completed by dario-piotrowicz** 2024-03-21 10:11 UTC
Labels: documentation, product:pages, content:edit
