### ISSUE TITLE
Add missing pages product to README

### ISSUE THREAD

**Issue by anthonygrimes** [cloudflare/cloudflare-docs#1078] opened 2021-04-07 08:23 UTC
### Expected Behavior
When navigating to the README.md I expect to see a complete listing of all products.

### Actual Behavior
When navigating to the README.md I do not see the product listing for the Pages product.

### Section that requires update
[This section](https://github.com/cloudflare/cloudflare-docs#products) requires updating to reflect the complete list of products, including Cloudfare Pages.

### Additional information
N/A

**Comment by KimJ15** [comment] 2021-04-07 18:35
Closing as a duplicate of https://github.com/cloudflare/cloudflare-docs/pull/1079

**Closed as completed by KimJ15** 2021-04-07 18:35 UTC
Labels: documentation
