### ISSUE TITLE
Bash code snippets include the leading `$` when pressing the copy to clipboard button

### ISSUE THREAD

**Issue by nathanclevenger** [cloudflare/cloudflare-docs#6095] opened 2022-10-03 12:45 UTC
### Example URL(s)

- https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/
- https://developers.cloudflare.com/workers/wrangler/get-started/
- https://developers.cloudflare.com/pub-sub/get-started/guide/

### Actual Behavior

```
$ curl --http2 -H "accept: application/dns-json" "https://1.1.1.1/dns-query?name=cloudflare.com" --next --http2 -H "accept: application/dns-json" "https://1.1.1.1/dns-query?name=example.com"
```
is copied to the clipboard, and when pasted into a terminal you receive:
```
zsh: command not found: $
```

In order to fix this, you have to remove the `$` from the beginning of the command, or go back to the documentation and manually select everything except the `$` to copy to the clipboard

### Expected Behavior

```
curl --http2 -H "accept: application/dns-json" "https://1.1.1.1/dns-query?name=cloudflare.com" --next --http2 -H "accept: application/dns-json" "https://1.1.1.1/dns-query?name=example.com"
```
Should be what is actually copied to the clipboard, so that it can be pasted directly into a terminal to execute:

```
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":true,"CD":false,"Question":[{"name":"cloudflare.com","type":1}],"Answer":[{"name":"cloudflare.com","type":1,"TTL":293,"data":"104.16.132.229"},{"name":"cloudflare.com","type":1,"TTL":293,"data":"104.16.133.229"}]}{"Status":0,"TC":false,"RD":true,"RA":true,"AD":true,"CD":false,"Question":[{"name":"example.com","type":1}],"Answer":[{"name":"example.com","type":1,"TTL":76027,"data":"93.184.216.34"}]}% 
```

**Comment by WalshyDev** [comment] 2022-10-03 18:29
Dupe of https://github.com/cloudflare/cloudflare-docs/issues/5474

**Closed as completed by WalshyDev** 2022-10-03 18:29 UTC
Labels: engineering
