### ISSUE TITLE
A couple of notes on "Build a Retrieval Augmented Generation (RAG) AI"

### ISSUE THREAD

**Issue by hay** [cloudflare/cloudflare-docs#11151] opened 2023-10-07 14:44 UTC
### Which Cloudflare product does this pertain to?

Workers AI

### Existing documentation URL(s)

https://developers.cloudflare.com/workers-ai/tutorials/build-a-retrieval-augmented-generation-ai/

### What changes are you suggesting?

A couple of suggestions for this tutorial:

1) Under "Create a new Worker project" the option with step 2 should not be "Select `"Hello World" script` but `"Hello World" Worker`
2) There seems to be a bug in the first code example: the `ai.run` function either wants a `messages` or a `prompt` property, but currently the code states `inputs` which i don't think is the correct API interface.
3) After step 4 ("Adding embeddings") the `wrangler` command is not preceeded by `npx`, which means it won't work if you haven't installed `wrangler` globally.
4) When i tried running the wrangler command to make a vector database i got an error "vectorize.not_entitled". This turns out to be an indication that you can only use this command if you've got a paid worker plan ([reference](https://github.com/cloudflare/workers-sdk/issues/4042)). I think it would be useful to mention this at the beginning of the tutorial, now i'm forced to take a paid plan to complete the tutorial.

**Comment by travisby** [comment] 2023-11-06 13:29
I can confirm issues 1, 3, and 4 from working through the tutorial this morning!  It looks like 2 has already been solved

**Comment by markashleybell** [comment] 2024-02-04 16:46
Yes, I also hit 1/3/4 just now. Issue 2 didn't come up for me either, so I assume that one is now fixed.

**Comment by kodster28** [comment] 2024-04-22 22:34
Howdy @hay, thanks for raising + providing the really detailed feedback (and apologies this sat for a bit).

In checking through your list, it appears that 1/2/3 have been previously addressed, but 4 has not. Pushing up #14192 to address the piece, which I think'd close out this issue.

**Closed as completed** 2024-04-23 13:14 UTC
Labels: documentation, content:edit, product:workers-ai

**Comment by hay** [comment] 2024-04-23 16:06
@kodster28 great, thanks!
