### ISSUE TITLE
ZT Docs' Managed Networks Python WebServer Example is Unreliable

### ISSUE THREAD

**Issue by metal0** [cloudflare/cloudflare-docs#9139] opened 2023-05-29 11:28 UTC
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/configure-warp/managed-networks#create-a-new-tls-endpoint

### Section that requires update

Python http server example

### What needs to change?

While the example works perfectly for normal requests, any request that terminates on the client-side before being fully processed by the server will cause a python error along the lines of "An existing connection was forcibly closed by the remote host".
After this error, it no longer accepts connections.

While this may be a edge-case, from my experience with the WARP client, it will often cause these errors and thus brick the server entirely, just from testing with a single client device on the network.
This makes the example provided unreliable at best.

### How should it change?

I haven't been able to fix this on a python level (I tried `try/except`on the handler for the example with no success), so unfortunately I'm not able to provide a solution.
I personally changed to a nodejs server for serving the cert and have had everything working so far.
Hopefully some python devs can provide some input, as I'm not one, and my stackoverflow googling attempts didn't help much either.

**Comment by ranbel** [comment] 2023-09-07 14:42
👋 @metal0 Thanks for opening this issue. Could you please detail the steps to reproduce the error?

**Comment by ranbel** [comment] 2023-09-18 20:29
I am closing this issue since we are unable to reproduce the Python error. Perhaps it has something to do with the Python version?
We have added an nginx web server example in case the Python script doesn't work: https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/configure-warp/managed-networks/#create-a-new-tls-endpoint

**Closed as completed by ranbel** 2023-09-18 20:29 UTC
Labels: documentation, Backlog, content:edit
