### ISSUE TITLE
Error getting origin cert: Client didn't specify origincert path when running from terminal

### ISSUE THREAD

**Issue by thphongv108** [cloudflare/cloudflare-docs#499] opened 2020-12-15 11:31 UTC
cloudflared.exe --hostname electro-locator-speeds-accommodate.trycloudflare.com --url localhost:5050

INFO[2020-12-15T18:28:47+07:00] Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp]
INFO[2020-12-15T18:28:47+07:00] Version 2020.12.0
INFO[2020-12-15T18:28:47+07:00] GOOS: windows, GOVersion: go1.15.6, GoArch: amd64
INFO[2020-12-15T18:28:47+07:00] Environment variables map[hostname:electro-locator-speeds-accommodate.trycloudflare.com proxy-dns-upstream:https://1.1.1.1/dns-query, https://1.0.0.1/dns-query url:localhost:5050]
INFO[2020-12-15T18:28:47+07:00] cloudflared will not automatically update on Windows systems.
INFO[2020-12-15T18:28:47+07:00] Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp]
ERROR[2020-12-15T18:28:47+07:00] You need to specify the origin certificate path with --origincert option, or set TUNNEL_ORIGIN_CERT environment variable. See https://developers.cloudflare.com/argo-tunnel/reference/arguments/ for more information.
ERROR[2020-12-15T18:28:47+07:00] Couldn't start tunnel: Error getting origin cert: Client didn't specify origincert path when running from terminal
Error getting origin cert: Client didn't specify origincert path when running from terminal

Thanks Team

**Comment by JanSchuerlein** [comment] 2021-01-21 15:17
Reported the same issue but with greater detail and more information.

When you try to run a tunnel without the admin cert.pem authentication file (which you can when you have a JSON credentials file for a specified tunnel), the error you specified occurs.

Link: [ISSUE-669](https://github.com/cloudflare/cloudflare-docs/issues/669)

**Solution**: Create a blank cert.pem file or a cert.pem file with random content and link to it.

**Comment by KimJ15** [comment] 2021-01-25 21:58
👋 @thphongv108 Thanks for opening this issue. Closing as a duplicate of https://github.com/cloudflare/cloudflare-docs/issues/669

**Closed as completed by KimJ15** 2021-01-25 21:58 UTC
