### ISSUE TITLE
The WP2Static plugin that the static WordPress site documentation relies upon is no longer available

### ISSUE THREAD

**Issue by svpn** [cloudflare/cloudflare-docs#131] opened 2020-10-21 01:03 UTC
**The WP2Static plugin has been closed since August 10, 2020 and is not available for download.**

**Comment by KimJ15** [comment] 2021-01-25 20:02
This is a duplicate of https://github.com/cloudflare/cloudflare-docs/issues/407

**Closed by KimJ15** 2021-01-25 20:02 UTC
